sudo: required
dist: trusty
language: go
## home folder is /home/travis/gopath/src/github.com/radanalyticsio/oshinko-cli
services:
- docker
stages:
  - Openshift tests
  - deploy

before_install:
- ./.travis.before.install.sh

env:
  global: OPENSHIFT_VERSION="v3.10"

jobs:
  include:
  - stage: Openshift tests
    name: openshift-spark
    script: make test-e2e-py

  - name: openshift-spark-py27
    script: make test-e2e-py27

  - name: openshift-spark-inc
    script: make -f Makefile.inc test-e2e-py

  - name: openshift-spark-py27-inc
    script: make -f Makefile.inc test-e2e-py27

  - name: openshift-spark-comp
    script: make -f Makefile.inc test-e2e-py-completed

  - name: openshift-spark-py27-comp
    script: make -f Makefile.inc test-e2e-py27-completed

  - stage: deploy
    name: "Push container images"
    script: ./.travis.release.images.sh

notifications:
 email:
   on_success: never
   on_failure: never
